swagger: '2.0'

info:
  version: 1.0.0
  title: Products API

consumes:
  - application/json
produces:
  - application/json

paths:
  /products:
    get:
      tags:
        - Products
      summary: Returns an array of all products in the database
      responses:
        '200':
          description: Products retrieved successfully!
        '404':
          description: No products found in database

    post:
      tags:
        - Products
      summary: Create a product
      parameters:
        - $ref: '#/models/product'
      responses:
        '201':
          description: Product created successfully!
        '400':
          description: Bad Request

  /products/{id}:
    get:
      tags:
        - Products
      summary: Retrieve a single product
      parameters:
        - $ref: '#/parameters/id'
      responses:
        '200':
          description: Product retrieved successfully!
        '400':
          description: Bad query string argument
        '404':
          description: Product does not exist

    put:
      tags:
        - Products
      summary: Update a product
      parameters:
        - $ref: '#/parameters/id'
        - $ref: '#/models/product'
      responses:
        '204':
          description: Product updated successfully!
        '400':
          description: Invalid Request
        '404':
          description: Product does not exist

    delete:
      tags:
        - Products
      summary: Delete a product
      parameters:
        - $ref: '#/parameters/id'
      responses:
        '204':
          description: Product deleted successfully!
        '404':
          description: Product does not exist

parameters:
  id:
    name: id
    type: string
    in: path
    required: true
    description: The id of the product

attributes:
  name:
    name: name
    type: string
    description: The name of the product
  price:
    name: price
    type: string
    description: The price of the product

models:
  product:
    name: product
    type: object
    in: body
    properties:
      name:
        $ref: '#/attributes/name'
      price:
        $ref: '#/attributes/price'
    required:
      - price
